### ISSUE TITLE
Sweep: When tracking donation, update fund with condition to check expected current fund total amount to avoid race conditions

### ISSUE THREAD

**Issue by yuriytkach** [yuriytkach/fundraiser-tracker#238]
### Details
When donation is tracked the fund's total amount is updated. Currently it simply adds donation amount to fund and then saves the fund. When saving we should use DynamoDB's conditional write to verify that current fund amount is what it was before added the donation amount. If condition fails, then we should retry at most 3 times with exponential backoff. On every retry we should recalculate new fund total based on new total that is present in DB.
Add integration test to check that update does not happen if current fund amount in DynamoDB is not what we expect.
Use 'final' keyword for local variables and function parameters.
Validate for unused imports and remove those.
Use 2 spaces indentation.

<details open>
<summary>Checklist</summary>

- [X] Modify `src/main/java/com/yuriytkach/tracker/fundraiser/service/DonationTracker.java` ✓ https://github.com/yuriytkach/fundraiser-tracker/commit/24dccca697ae6429f1fa207d724a0514d0df7883 [Edit](https://github.com/yuriytkach/fundraiser-tracker/edit/sweep/when_tracking_donation_update_fund_with/src/main/java/com/yuriytkach/tracker/fundraiser/service/DonationTracker.java#L25-L59)
- [X] Running GitHub Actions for `src/main/java/com/yuriytkach/tracker/fundraiser/service/DonationTracker.java` ✓  [Edit](https://github.com/yuriytkach/fundraiser-tracker/edit/sweep/when_tracking_donation_update_fund_with/src/main/java/com/yuriytkach/tracker/fundraiser/service/DonationTracker.java#L25-L59)
- [X] Modify `src/main/java/com/yuriytkach/tracker/fundraiser/service/dynamodb/DynamoDbFundStorageClient.java` ✓ https://github.com/yuriytkach/fundraiser-tracker/commit/fb38d2e59a491df98dbaf2de005f4b5a7b97485b [Edit](https://github.com/yuriytkach/fundraiser-tracker/edit/sweep/when_tracking_donation_update_fund_with/src/main/java/com/yuriytkach/tracker/fundraiser/service/dynamodb/DynamoDbFundStorageClient.java#L99-L235)
- [X] Running GitHub Actions for `src/main/java/com/yuriytkach/tracker/fundraiser/service/dynamodb/DynamoDbFundStorageClient.java` ✓  [Edit](https://github.com/yuriytkach/fundraiser-tracker/edit/sweep/when_tracking_donation_update_fund_with/src/main/java/com/yuriytkach/tracker/fundraiser/service/dynamodb/DynamoDbFundStorageClient.java#L99-L235)
- [X] Create `src/test/java/com/yuriytkach/tracker/fundraiser/service/DonationTrackerIntegrationTest.java` ✓ https://github.com/yuriytkach/fundraiser-tracker/commit/2b3dd09e2906ee90d78ebb4591ab4f39a2d83cf6 [Edit](https://github.com/yuriytkach/fundraiser-tracker/edit/sweep/when_tracking_donation_update_fund_with/src/test/java/com/yuriytkach/tracker/fundraiser/service/DonationTrackerIntegrationTest.java)
- [X] Running GitHub Actions for `src/test/java/com/yuriytkach/tracker/fundraiser/service/DonationTrackerIntegrationTest.java` ✓  [Edit](https://github.com/yuriytkach/fundraiser-tracker/edit/sweep/when_tracking_donation_update_fund_with/src/test/java/com/yuriytkach/tracker/fundraiser/service/DonationTrackerIntegrationTest.java)
</details>
